<?xml version="1.0" encoding="utf-8"?><Database Name="SystemManage" Class="DatasystemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=gun;Initial Catalog=SystemManage;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SystemManageConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Manage" Member="Manages">
    <Type Name="Manage">
      <Column Name="ID_Project" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ID_User" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Project_Manage" Member="Project" ThisKey="ID_Project" OtherKey="ID_Project" Type="Project" IsForeignKey="true" />
      <Association Name="User_name_Manage" Member="User_name" ThisKey="ID_User" OtherKey="ID_User" Type="User_name" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Processes" Member="Processes">
    <Type Name="Process">
      <Column Name="Name_Processes" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Process_Sub_Project" Member="Sub_Projects" ThisKey="Name_Processes" OtherKey="Name_Processes" Type="Sub_Project" />
    </Type>
  </Table>
  <Table Name="dbo.Project" Member="Projects">
    <Type Name="Project">
      <Column Name="ID_Project" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name_Project" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Project_Manage" Member="Manages" ThisKey="ID_Project" OtherKey="ID_Project" Type="Manage" />
      <Association Name="Project_Sub_Project" Member="Sub_Projects" ThisKey="ID_Project" OtherKey="ID_Project" Type="Sub_Project" />
    </Type>
  </Table>
  <Table Name="dbo.Sub_Project" Member="Sub_Projects">
    <Type Name="Sub_Project">
      <Column Name="Subrasks_Project" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Dead_Line" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Comment_Bymanager" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Issue" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Name_Processes" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ID_Project" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="progress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Process_Sub_Project" Member="Process" ThisKey="Name_Processes" OtherKey="Name_Processes" Type="Process" IsForeignKey="true" />
      <Association Name="Project_Sub_Project" Member="Project" ThisKey="ID_Project" OtherKey="ID_Project" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.User_name" Member="User_names">
    <Type Name="User_name">
      <Column Name="ID_User" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="User_name_Manage" Member="Manages" ThisKey="ID_User" OtherKey="ID_User" Type="Manage" />
    </Type>
  </Table>
</Database>